### ISSUE TITLE
PATCH NEEDED FOR TO EXTEND THE CHECKOUT DATE FOR NON ACTIVE CUSTOMER 

### ISSUE THREAD

**Issue by vishwan** [SSOMENSREPO/EI-PATCH#11]
2318 Evelyn Eunnah Lee

Extend the End date from 12/8/15 to 16/8/15 .

**Comment by vishwan** [comment]
3001 MIGUEL .


EXTEND THE END DATE FROM 31/8/15 TO 16/9/15

**Comment by DHANDAPANISATTANATHAN** [comment]
@DHIVYAARJUAN 

Write those patch and dely immediately.

**Comment by vishwan** [comment]
2218 WANG YANG - ACTIVE CUSTOMER 

EXTEND THE START DATE FROM 9/9/15 TO 13/9/15

**Comment by DHANDAPANISATTANATHAN** [comment]
DEFECT OWNER:@DHIVYAARJUAN 

Missed to update LP and Quarter Cal.Update and re dely

**Comment by DHIVYAARJUAN** [comment]
updated lease period and quarters above mentioned customers
https://github.com/SSOMENSREPO/EI-PATCH/releases/tag/v1.2

* status:**delivered**

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: **to_be_tested**

Test in uat

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: **verified**

Tested and verified in Uat

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: **Integrated**

Int in Prod

**Comment by DHANDAPANISATTANATHAN** [comment]
* status: **t0_be_tested**

@vishwan

**Comment by vishwan** [comment]
#verified
