### ISSUE TITLE
Run Query with Date Range & Amount Range

### ISSUE THREAD

**Issue by vishwan** [SSOMENSREPO/EI-PATCH#17]
Run Query with Date range - July 2015 to Nov 2015 
Amount Range - $700 to $800
Chk in DB

**Comment by DHANDAPANISATTANATHAN** [comment]
@DHIVYAARJUAN

**Comment by DHANDAPANISATTANATHAN** [comment]
@vishwan 

https://docs.google.com/spreadsheets/d/1_Wr-JYhIzic04gWZhog2TNqyzz3zqrIFhfkXTxlXQrY/edit#gid=0
