### ISSUE TITLE
PATCH NEED TO UPDATE START DATE OF 0523 Jirakulpattana Suthinand 

### ISSUE THREAD

**Issue by vishwan** [SSOMENSREPO/EI-PATCH#19]
Pls modify 0523 Jira start date to 27 Nov 2015

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
PATCH COMPLETED TO UPDATE SDATE FOR JIRA CUSTOMER

GITHUB LINK : https://github.com/SSOMENSREPO/EI-PATCH/releases/tag/V1.8

status : **delivered**

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be_tested

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: defect
@RAJALAKSHMIRAJKUMAR 
Missed LP and QUARTER UPDATE

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
issue fixed.

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be_tested

Test in uat

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: verified

SD updated and LP AND QUARTER ALOS

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: Integrated

Int in prod

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be _tested

@vishwan 

Check in PROD

**Comment by vishwan** [comment]
#verified
