### ISSUE TITLE
CUSTOMERS DINT GET TERMINATED .

### ISSUE THREAD

**Issue by vishwan** [SSOMENSREPO/EI-PATCH#21]
Few Customers dint Terminate via trigger. So pls unblock it asap
![unterm](https://cloud.githubusercontent.com/assets/12405667/11552481/06bf560c-99c0-11e5-891a-312f870dcfa1.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
@RAJALAKSHMIRAJKUMAR 

Check the above customer not terminated in prod.

I gave customer tables to you, Check and let me know.Why PTD customer not terminated!

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
I checked auto termination sp via form with current prod data. This customers terminated correctly.

**Comment by DHANDAPANISATTANATHAN** [comment]
Gd!. I found connection issue in script.used old db name.

Now fixed!

Defect owner: SN

**Comment by DHANDAPANISATTANATHAN** [comment]
@vishwan 

If you want trigger will terminate tmrw. these customer.

Otherwise manually will terminate

# status: Fixed

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be_tested

@vishwan
