### ISSUE TITLE
EI DD SHEET. .Unbold the "BATTERY CHANGE" term

### ISSUE THREAD

**Issue by vishwan** [SSOMENSREPO/EI-PATCH#22]
Just Unbold & Update to Lower Case - " BATTERY CHANGE"

![dd](https://cloud.githubusercontent.com/assets/12405667/11552613/794bd62c-99c1-11e5-99e0-bd990ce39052.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
CHNGE TO UNBOLD & LOWER CASE

**Comment by SaradambalMunusamy** [comment]
closed and delivered in https://github.com/SSOMENSREPO/EI-PHP-CRM/releases/tag/v0.7

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be_tested

Test in uat

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: verified

Tested in uat DD changes unbold and lower case, customer name search sorting for period, whilte font not come working fine

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: Integrated

Int in EI PROD

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: to_be_tested

@vishwan 

Check in PROD

**Comment by vishwan** [comment]
#verified
