### ISSUE TITLE
ACTIVE CUST LIST : LINK IS NOT ATTACHED 

### ISSUE THREAD

**Issue by vishwan** [SSOMENSREPO/EI-PATCH#23]
LINK IS NOT ATTACHED . WHILE GENERATING ACTIVE CUST LIST 

FYI:
HELLO VISWANATH.N

, PLEASE FIND ATTACHED THE CURRENT :

#regression

![active](https://cloud.githubusercontent.com/assets/12405667/11554036/61024c00-99cf-11e5-9f17-c91bd45d71ce.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
@SaradambalMunusamy 

Check and reply this issue!

**Comment by DHANDAPANISATTANATHAN** [comment]
In connection file old uat db name used. Now changed the uat db name and deployed
