### ISSUE TITLE
CC AUTO TERMINATION TRIGGER NOT DONE 

### ISSUE THREAD

**Issue by vishwan** [SSOMENSREPO/EI-PATCH#25]
Chk un terminated non active cust. auto termination trigger. Not functioning . 

![cc term](https://cloud.githubusercontent.com/assets/12405667/12346278/f8b4c372-bb8d-11e5-8f9f-e0f72bd6e0b0.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
@vishwan 

In email list. We used expats gmail id in prod DB. So that after SA not work.

Now email id updated via form, No issue will come
