### ISSUE TITLE
DEFECT IN AC PATCH

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/EI-PATCH#3]
<h3>DEFECT OWNER: SN, DIV, RL
ALL ACTIVE CUSTOMER COMMETNS MISSED.

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
ISSUE FIXED & DELIVERED.

DRIVE LINK : https://github.com/SSOMENSREPO/EI-PATCH/releases/tag/v0.4
