### ISSUE TITLE
UPDATE OCBC OWNERS RENT UNTIL JULY FOR ALL UNITS 

### ISSUE THREAD

**Issue by vishwan** [SSOMENSREPO/EI-PATCH#8]
Download OCBC Owners rent for all Units =[Owners Monthly Rent-Monthly Giros Payment] from April 2015 to till date & extract it in corresp. SS

**Comment by DHANDAPANISATTANATHAN** [comment]
TASK OWNER; DIV

**Comment by DHIVYAARJUAN** [comment]
Prepared ss for OCBC Owners  rent  details for all units from April-2015 to till date
ss link: https://docs.google.com/spreadsheets/d/1q2w_wsEyjd9z9U_pAKUiyU-lhkoRhcl5p4Og5ybep_E/edit#gid=1820736884

* status :  **delivered**

**Comment by DHANDAPANISATTANATHAN** [comment]
* **OWNER : VVA**

**Comment by vishwan** [comment]
EXTRACT SAIL 5522 OWNERS RENT 

START DATE - JAN 2013 TO TILL DATE

**Comment by DHANDAPANISATTANATHAN** [comment]
@DHIVYAARJUAN

**Comment by DHIVYAARJUAN** [comment]
ABOVE TASK ASSIGNED TO ELAMATHI

**Comment by DHIVYAARJUAN** [comment]
ELAMATHI DELIVERED EXTRACT SAIL 5522 OWNERS RENT IN BELOW SS

https://docs.google.com/spreadsheets/d/1t5iyH6ZpgHxtrOolyrIJIqjXrLvUkMkyUUjNhawhJ7s/edit#gid=0

**Comment by DHANDAPANISATTANATHAN** [comment]
@vishwan 

* Status: Done

**Comment by vishwan** [comment]
Remove the charges, select only amounts greater than 10$!

**Comment by DHIVYAARJUAN** [comment]
ELAMATHI DID ABOVE CHANGES AND DELIVERED IN BELOW LINK

https://docs.google.com/spreadsheets/d/1t5iyH6ZpgHxtrOolyrIJIqjXrLvUkMkyUUjNhawhJ7s/edit#gid=1130832142

* status :**delivered**

**Comment by vishwan** [comment]
1.EXTRACT SAIL 0518  OWNERS RENT[Owners Monthly Rent-Monthly Giros Payment] 

START DATE - JAN 2013 TO TILL DATE 
Need Owners rent Immediate for 0518  

2.  OCBC Owners rent for all Units exclude 0518 unit
From Jan 2013 to Till Date

**Comment by DHIVYAARJUAN** [comment]
extracted unit owners rental records from jan 2013 to till date for all units

refer below ss:
https://docs.google.com/spreadsheets/d/1bDDHXzY7mYDD6V6sD08oJwTq7M9nPen-XFMufQ5EmGI/edit#gid=1658584402

* status:**delivered**

**Comment by vishwan** [comment]
Need Owners rent of  SAIL 0518 

JAN 2013 TO TILL DATE . 

[Remove Giro charges, select only amounts greater than $10]

**Comment by DHANDAPANISATTANATHAN** [comment]
@vishwan 

user REPORT menu --> OCBC ---> OWNER RENTAL. You ll get the result!

**Comment by vishwan** [comment]
Yes Yes.I knw. But dnt have access in PROD .

**Comment by DHANDAPANISATTANATHAN** [comment]
@vishwan 

BB has access.or Get access from client in PROD!

**Comment by vishwan** [comment]
Download OCBC Owners rent for all Units =[Owners Monthly Rent-Monthly Giros Payment] from Nov to till date & extract it in corresp. SS

**Comment by vishwan** [comment]
Need Owners rent of SAIL 1915

JAN 2013 TO TILL DATE .

Extract in Corresponding SS.

**Comment by DHANDAPANISATTANATHAN** [comment]
@RAJALAKSHMIRAJKUMAR 

Do this

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
extracted unit owners rental records from jan 2013 to till date for sail 1915

refer below ss:
https://docs.google.com/spreadsheets/d/1bDDHXzY7mYDD6V6sD08oJwTq7M9nPen-XFMufQ5EmGI/edit?ts=568a49ed#gid=1577480288

sheet name : SAIL_1915

status: **delivered**

**Comment by DHANDAPANISATTANATHAN** [comment]
@vishwan

**Comment by vishwan** [comment]
@DHANDAPANISATTANATHAN   

Remove all Records which less than $10  .[OBR_DEBIT_AMOUNT]

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
Removed records which is less than $10

status: **done**
